-- Rebuild checklist_templates from provided Excel files (EN only, rooms normalized)
begin;
delete from checklist_templates where apartment_type in ('T2','T2+1','T3','T3+1');
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Snag list Inspection', null, 1);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Date', null, 2);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Owner', null, 3);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Bedrooms', null, 4);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Hall', null, 5);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Walls / wood panels', null, 6);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Ceiling', null, 7);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Floor & skirting', null, 8);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Door', null, 9);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Lights', null, 10);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Other', null, 11);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Kitchen', null, 12);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Microwave', null, 13);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Fridge & Wine fridge', null, 14);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Cooker/Hob/CookTop', null, 15);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Oven', null, 16);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Dishwasher', null, 17);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Washer/Dryer', null, 18);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Walls', null, 19);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Ceiling', null, 20);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Counters', null, 21);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Cabinets', null, 22);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Sliding door', null, 23);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Blinds', null, 24);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Floor & skirting', null, 25);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Lights', null, 26);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Other', null, 27);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Dining Room', null, 28);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Walls / wood panels', null, 29);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Ceiling', null, 30);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Floor & skirting', null, 31);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Sliding door', null, 32);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Plugs', null, 33);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Blinds', null, 34);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Lights', null, 35);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Other', null, 36);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Living Room', null, 37);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Walls', null, 38);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Ceiling', null, 39);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Floor & skirting', null, 40);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Sliding door', null, 41);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Plugs', null, 42);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Blinds', null, 43);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Lights', null, 44);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Other', null, 45);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Balcony - Pool side', null, 46);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Walls', null, 47);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Ceiling', null, 48);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Tiles', null, 49);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Glass railing', null, 50);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Lights', null, 51);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Other', null, 52);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Suite Bedroom', null, 53);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Walls', null, 54);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Ceiling', null, 55);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Floor & skirting', null, 56);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Wardrobe', null, 57);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Plugs', null, 58);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Blinds', null, 59);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Door', null, 60);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Sliding door', null, 61);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Lights', null, 62);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Other', null, 63);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Suite Bathroom', null, 64);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Shower Cubicle', null, 65);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Shower Doors', null, 66);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Toilet', null, 67);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Mirror', null, 68);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Cabinet & drawers', null, 69);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Basin', null, 70);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Taps', null, 71);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Ceiling', null, 72);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Walls & Tiles', null, 73);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Floor & skirting', null, 74);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Door', null, 75);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Lights', null, 76);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Other', null, 77);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Bedroom 2', null, 78);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Walls', null, 79);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Ceiling', null, 80);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Floor & skirting', null, 81);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Wardrobe', null, 82);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Plugs', null, 83);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Blinds', null, 84);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Door', null, 85);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Sliding door', null, 86);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Lights', null, 87);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Other', null, 88);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Bathroom 2', null, 89);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Shower Cubicle', null, 90);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Shower Doors', null, 91);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Toilet', null, 92);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Mirror', null, 93);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Cabinet & drawers', null, 94);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Basin', null, 95);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Taps', null, 96);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Ceiling', null, 97);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Walls & Tiles', null, 98);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Floor & skirting', null, 99);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Door', null, 100);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Lights', null, 101);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Other', null, 102);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Balcony - Back', null, 103);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Walls', null, 104);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Ceiling', null, 105);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Tiles', null, 106);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Glass railing', null, 107);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Outside Patio Storage', 'Lights', null, 108);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Snag list Inspection', null, 1);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Date', null, 2);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Owner', null, 3);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Bedrooms', null, 4);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Hall', null, 5);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Walls', null, 6);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Ceiling', null, 7);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Floor & skirting', null, 8);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Door', null, 9);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Lights', null, 10);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Other', null, 11);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Pantry/Laundry', null, 12);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Walls', null, 13);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Ceiling', null, 14);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Floor & skirting', null, 15);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Door', null, 16);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Cabinets', null, 17);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Washer/Dryer', null, 18);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Lights', null, 19);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Other', null, 20);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Kitchen', null, 21);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Microwave', null, 22);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Fridge & Wine fridge', null, 23);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Cooker/Hob/CookTop', null, 24);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Oven', null, 25);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Dishwasher', null, 26);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Walls', null, 27);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Ceiling', null, 28);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Counters', null, 29);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Cabinets', null, 30);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Sliding door', null, 31);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Blinds', null, 32);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Floor & skirting', null, 33);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Lights', null, 34);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Other', null, 35);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Dining Room', null, 36);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Walls / wood panels', null, 37);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Ceiling', null, 38);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Floor & skirting', null, 39);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Sliding door', null, 40);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Plugs', null, 41);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Blinds', null, 42);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Lights', null, 43);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Other', null, 44);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Living Room', null, 45);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Walls', null, 46);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Ceiling', null, 47);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Floor & skirting', null, 48);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Sliding door', null, 49);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Plugs', null, 50);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Blinds', null, 51);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Lights', null, 52);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Other', null, 53);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Balcony - Pool side', null, 54);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Walls', null, 55);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Ceiling', null, 56);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Tiles', null, 57);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Glass railing', null, 58);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Lights', null, 59);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Other', null, 60);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Suite Bedroom', null, 61);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Walls', null, 62);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Ceiling', null, 63);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Floor & skirting', null, 64);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Wardrobe', null, 65);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Plugs', null, 66);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Blinds', null, 67);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Door', null, 68);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Sliding door', null, 69);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Lights', null, 70);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Other', null, 71);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Suite Bathroom', null, 72);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Shower Cubicle', null, 73);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Shower Doors', null, 74);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Toilet', null, 75);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Mirror', null, 76);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Cabinet & drawers', null, 77);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Basin', null, 78);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Taps', null, 79);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Ceiling', null, 80);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Walls & Tiles', null, 81);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Floor & skirting', null, 82);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Door', null, 83);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Lights', null, 84);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Other', null, 85);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Bedroom 2', null, 86);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Walls', null, 87);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Ceiling', null, 88);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Floor & skirting', null, 89);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Wardrobe', null, 90);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Plugs', null, 91);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Blinds', null, 92);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Door', null, 93);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Sliding door', null, 94);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Lights', null, 95);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Other', null, 96);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Bathroom 2', null, 97);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Shower Cubicle', null, 98);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Shower Doors', null, 99);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Toilet', null, 100);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Mirror', null, 101);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Cabinet & drawers', null, 102);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Basin', null, 103);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Taps', null, 104);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Ceiling', null, 105);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Walls & Tiles', null, 106);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Floor & skirting', null, 107);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Door', null, 108);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Lights', null, 109);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Other', null, 110);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Study/Bedroom 3', null, 111);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Walls', null, 112);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Ceiling', null, 113);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Floor & skirting', null, 114);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Wardrobe', null, 115);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Plugs', null, 116);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Blinds', null, 117);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Door', null, 118);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Sliding door', null, 119);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Lights', null, 120);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Other', null, 121);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Balcony - Back', null, 122);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Walls', null, 123);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Ceiling', null, 124);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Tiles', null, 125);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Hall', 'Glass railing', null, 126);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2+1', 'Outside Patio Storage', 'Lights', null, 127);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Snag list Inspection', null, 1);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Date', null, 2);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Owner', null, 3);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Bedrooms', null, 4);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Hall', null, 5);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Walls / wood panels', null, 6);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Ceiling', null, 7);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Floor & skirting', null, 8);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Door', null, 9);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Lights', null, 10);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Other', null, 11);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Kitchen', null, 12);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Microwave', null, 13);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Fridge & Wine fridge', null, 14);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Cooker/Hob/CookTop', null, 15);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Oven', null, 16);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Dishwasher', null, 17);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Washer/Dryer', null, 18);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Walls', null, 19);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Ceiling', null, 20);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Counters', null, 21);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Cabinets', null, 22);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Sliding door', null, 23);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Blinds', null, 24);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Floor & skirting', null, 25);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Lights', null, 26);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Other', null, 27);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Dining Room', null, 28);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Walls / wood panels', null, 29);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Ceiling', null, 30);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Floor & skirting', null, 31);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Sliding door', null, 32);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Plugs', null, 33);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Blinds', null, 34);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Lights', null, 35);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Other', null, 36);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Living Room', null, 37);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Walls', null, 38);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Ceiling', null, 39);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Floor & skirting', null, 40);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Sliding door', null, 41);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Plugs', null, 42);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Blinds', null, 43);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Lights', null, 44);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Other', null, 45);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Balcony - Pool side', null, 46);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Walls', null, 47);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Ceiling', null, 48);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Tiles', null, 49);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Glass railing', null, 50);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Lights', null, 51);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Other', null, 52);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Suite Bedroom', null, 53);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Walls', null, 54);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Ceiling', null, 55);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Floor & skirting', null, 56);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Wardrobe', null, 57);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Plugs', null, 58);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Blinds', null, 59);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Door', null, 60);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Sliding door', null, 61);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Lights', null, 62);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Other', null, 63);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Suite Bathroom', null, 64);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Shower Cubicle', null, 65);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Shower Doors', null, 66);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Toilet', null, 67);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Mirror', null, 68);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Cabinet & drawers', null, 69);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Basin', null, 70);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Taps', null, 71);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Ceiling', null, 72);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Walls & Tiles', null, 73);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Floor & skirting', null, 74);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Door', null, 75);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Lights', null, 76);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Other', null, 77);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Bedroom 2', null, 78);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Walls', null, 79);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Ceiling', null, 80);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Floor & skirting', null, 81);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Wardrobe', null, 82);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Plugs', null, 83);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Blinds', null, 84);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Door', null, 85);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Sliding door', null, 86);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Lights', null, 87);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Other', null, 88);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Bathroom 2', null, 89);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Shower Cubicle', null, 90);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Shower Doors', null, 91);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Toilet', null, 92);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Mirror', null, 93);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Cabinet & drawers', null, 94);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Basin', null, 95);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Taps', null, 96);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Ceiling', null, 97);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Walls & Tiles', null, 98);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Floor & skirting', null, 99);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Door', null, 100);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Lights', null, 101);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Other', null, 102);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Bedroom 3', null, 103);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Walls', null, 104);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Ceiling', null, 105);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Floor & skirting', null, 106);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Wardrobe', null, 107);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Plugs', null, 108);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Blinds', null, 109);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Door', null, 110);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Sliding door', null, 111);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Lights', null, 112);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Other', null, 113);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Balcony - Back', null, 114);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Walls', null, 115);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Ceiling', null, 116);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Tiles', null, 117);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Hall', 'Glass railing', null, 118);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3', 'Outside Patio Storage', 'Lights', null, 119);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Snag list Inspection', null, 1);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Date', null, 2);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Owner', null, 3);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Bedrooms', null, 4);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Hall', null, 5);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls', null, 6);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 7);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Floor & skirting', null, 8);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Door', null, 9);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 10);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Cupboards', null, 11);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 12);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Other', null, 13);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Kitchen', null, 14);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Microwave', null, 15);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Fridge & Wine fridge', null, 16);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Cooker/Hob/CookTop', null, 17);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Oven', null, 18);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Dishwasher', null, 19);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Washer/Dryer', null, 20);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls', null, 21);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 22);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Counters', null, 23);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Cabinets', null, 24);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Sliding door', null, 25);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Blinds', null, 26);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Floor & skirting', null, 27);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 28);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Other', null, 29);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Dining Room', null, 30);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls / wood panels', null, 31);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 32);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Floor & skirting', null, 33);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Sliding door', null, 34);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Plugs', null, 35);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Blinds', null, 36);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 37);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Other', null, 38);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Living Room', null, 39);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls', null, 40);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 41);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Floor & skirting', null, 42);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Sliding door', null, 43);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Plugs', null, 44);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Blinds', null, 45);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 46);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Other', null, 47);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Balcony - Front', null, 48);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls', null, 49);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 50);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Tiles', null, 51);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Glass railing', null, 52);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 53);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Other', null, 54);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Suite Bedroom', null, 55);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls', null, 56);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 57);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Floor & skirting', null, 58);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Wardrobe', null, 59);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Plugs', null, 60);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Blinds', null, 61);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Door', null, 62);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Sliding door', null, 63);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 64);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Other', null, 65);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Suite Bathroom', null, 66);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Shower Cubicle', null, 67);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Shower Doors', null, 68);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Toilet', null, 69);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Mirror', null, 70);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Cabinet & drawers', null, 71);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Basin', null, 72);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Taps', null, 73);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 74);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls & Tiles', null, 75);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Floor & skirting', null, 76);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Door', null, 77);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 78);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Other', null, 79);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Bedroom 2', null, 80);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls', null, 81);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 82);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Floor & skirting', null, 83);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Wardrobe', null, 84);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Plugs', null, 85);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Blinds', null, 86);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Door', null, 87);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Sliding door', null, 88);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 89);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Other', null, 90);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Guest Bathroom', null, 91);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Shower Cubicle', null, 92);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Shower Doors', null, 93);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Toilet', null, 94);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Mirror', null, 95);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Cabinet & drawers', null, 96);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Basin', null, 97);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Taps', null, 98);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 99);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls & Tiles', null, 100);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Floor & skirting', null, 101);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Door', null, 102);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 103);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Other', null, 104);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Bedroom 3', null, 105);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls', null, 106);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 107);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Floor & skirting', null, 108);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Wardrobe', null, 109);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Plugs', null, 110);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Blinds', null, 111);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Door', null, 112);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Sliding door', null, 113);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 114);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Other', null, 115);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Bedroom 4', null, 116);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls', null, 117);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 118);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Floor & skirting', null, 119);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Wardrobe', null, 120);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Plugs', null, 121);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Blinds', null, 122);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Door', null, 123);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Sliding door', null, 124);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 125);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Other', null, 126);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'B4 on - suite bathroom', null, 127);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Shower Cubicle', null, 128);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Shower Doors', null, 129);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Toilet', null, 130);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Mirror', null, 131);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Cabinet & drawers', null, 132);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Basin', null, 133);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Taps', null, 134);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 135);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls & Tiles', null, 136);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Floor & skirting', null, 137);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Door', null, 138);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Lights', null, 139);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Other', null, 140);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Balcony - Pool side', null, 141);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Walls', null, 142);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Ceiling', null, 143);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Tiles', null, 144);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Hall', 'Glass railing', null, 145);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T3+1', 'Outside Patio Storage', 'Lights', null, 146);
commit;
