-- Reset T2 checklist from PO-provided list (EN only, normalized)
begin;
delete from checklist_templates where apartment_type = 'T2';
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Walls / wood panels', null, 1);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Ceiling', null, 2);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Floor & skirting', null, 3);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Door', null, 4);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Lights', null, 5);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Hall', 'Other', null, 6);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Microwave', null, 7);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Fridge & Wine fridge', null, 8);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Cooker/Hob/CookTop', null, 9);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Oven', null, 10);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Dishwasher', null, 11);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Washer/Dryer', null, 12);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Walls', null, 13);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Ceiling', null, 14);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Counters', null, 15);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Cabinets', null, 16);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Sliding door', null, 17);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Blinds', null, 18);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Floor & skirting', null, 19);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Lights', null, 20);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Kitchen', 'Other', null, 21);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Dining Room', 'Walls / wood panels', null, 22);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Dining Room', 'Ceiling', null, 23);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Dining Room', 'Floor & skirting', null, 24);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Dining Room', 'Sliding door', null, 25);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Dining Room', 'Plugs', null, 26);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Dining Room', 'Blinds', null, 27);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Dining Room', 'Lights', null, 28);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Dining Room', 'Other', null, 29);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Living Room', 'Walls', null, 30);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Living Room', 'Ceiling', null, 31);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Living Room', 'Floor & skirting', null, 32);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Living Room', 'Sliding door', null, 33);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Living Room', 'Plugs', null, 34);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Living Room', 'Blinds', null, 35);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Living Room', 'Lights', null, 36);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Living Room', 'Other', null, 37);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Pool side', null, 38);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Pool side - Walls', null, 39);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Pool side - Ceiling', null, 40);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Pool side - Tiles', null, 41);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Pool side - Glass railing', null, 42);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Pool side - Lights', null, 43);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Pool side - Other', null, 44);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bedroom', 'Walls', null, 45);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bedroom', 'Ceiling', null, 46);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bedroom', 'Floor & skirting', null, 47);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bedroom', 'Wardrobe', null, 48);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bedroom', 'Plugs', null, 49);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bedroom', 'Blinds', null, 50);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bedroom', 'Door', null, 51);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bedroom', 'Sliding door', null, 52);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bedroom', 'Lights', null, 53);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bedroom', 'Other', null, 54);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Shower Cubicle', null, 55);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Shower Doors', null, 56);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Toilet', null, 57);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Mirror', null, 58);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Cabinet & drawers', null, 59);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Basin', null, 60);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Taps', null, 61);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Ceiling', null, 62);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Walls & Tiles', null, 63);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Floor & skirting', null, 64);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Door', null, 65);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Lights', null, 66);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Suite Bathroom', 'Other', null, 67);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bedroom 2', 'Walls', null, 68);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bedroom 2', 'Ceiling', null, 69);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bedroom 2', 'Floor & skirting', null, 70);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bedroom 2', 'Wardrobe', null, 71);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bedroom 2', 'Plugs', null, 72);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bedroom 2', 'Blinds', null, 73);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bedroom 2', 'Door', null, 74);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bedroom 2', 'Sliding door', null, 75);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bedroom 2', 'Lights', null, 76);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bedroom 2', 'Other', null, 77);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Shower Cubicle', null, 78);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Shower Doors', null, 79);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Toilet', null, 80);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Mirror', null, 81);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Cabinet & drawers', null, 82);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Basin', null, 83);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Taps', null, 84);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Ceiling', null, 85);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Walls & Tiles', null, 86);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Floor & skirting', null, 87);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Door', null, 88);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Lights', null, 89);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Bathroom 2', 'Other', null, 90);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Back', null, 91);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Back - Walls', null, 92);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Back - Ceiling', null, 93);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Back - Tiles', null, 94);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Back - Glass railing', null, 95);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Back - Outside Patio Storage', null, 96);
insert into checklist_templates (apartment_type, room_type, item_description, item_description_pt, order_sequence) values ('T2', 'Balcony', 'Back - Lights', null, 97);
commit;
